# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# Nombre del workflow
name: Java CI with Maven

on:
  # Cuando queremos que se ejecute este workflow
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Stages en Jenkins
jobs:
  # Nombre del stage
  build:
    # Donde queremos que se corra
    runs-on: ubuntu-latest

    steps:
    # Nombre del paso
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber-report.json"
